style = "blue"

always_use_return = true
annotate_untyped_fields_with_any = true
import_to_using = true
indent = 2
margin = 100
whitespace_typedefs = true
remove_extra_newlines = true
short_to_long_function_def = false
always_for_in = true
